# Generated by Django 2.1.7 on 2019-03-09 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleLips',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image_name', models.CharField(max_length=100)),
                ('image_in_base_64', models.TextField()),
                ('rgb_numpy', picklefield.fields.PickledObjectField(editable=False)),
                ('face_landmarks', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleNoses',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image_name', models.CharField(max_length=100)),
                ('image_in_base_64', models.TextField()),
                ('rgb_numpy', picklefield.fields.PickledObjectField(editable=False)),
                ('face_landmarks', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('input_photo', models.TextField()),
                ('photo_in_rgb', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('number_of_detected_faces', models.IntegerField()),
                ('face_landmarks', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
